repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(docker-compose\.test\.yml|mkdocs\.yml)$  # pyyaml can't handle custom YAML tags
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        exclude: ^tak/

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests/ -v
        language: system
        pass_filenames: false
        always_run: true
