#!/bin/sh
# video-cot.sh — Start a test video stream and announce it to TAK Server
#
# With no arguments, starts a test pattern stream on MediaMTX and pushes
# a CoT marker to TAK Server using RTSP defaults. All options can be
# overridden — run with --help to see them.
#
# Requires: openssl, python3, ffmpeg
# Certs:    Uses client certs from tak/certs/files/ (generated by TAK Server)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Defaults ─────────────────────────────────────────────────────────────

SERVER_ADDRESS=$(grep '^SERVER_ADDRESS=' "$SCRIPT_DIR/.env" 2>/dev/null | cut -d= -f2)
CERT_DIR="$SCRIPT_DIR/tak/certs/files"
CERT_NAME="nodered"  # nodered cert is in tak_ROLE_ADMIN, reaches all clients
CERT_PASS="atakatak" # TAK Server default cert password

STREAM_PATH="live/test1"
PROTOCOL="rtsp"
PORT="8554"
LAT="38.8977"
LON="-77.0365"
HAE="0"
CALLSIGN="FastTAK Test Stream"
STALE_MINUTES="60"
FOV="60"
AZIMUTH="0"
RANGE="500"
VIDEO_FILE=""
TEST_STREAM="true"

# ── Help ─────────────────────────────────────────────────────────────────

show_help() {
    cat <<'HELP'
Usage: ./video-cot.sh [options]

Starts a test video stream on MediaMTX and announces it to TAK Server
as a CoT sensor marker. With no arguments, runs a full test using RTSP
with a test pattern near the White House.

Options:
  --path <path>            MediaMTX stream path (default: live/test1)
  --protocol <proto>       Stream protocol: rtsp (default), http (HLS), rtmp
  --port <port>            Stream port (default: 8554 for RTSP, 8888 for HLS)
  --lat <latitude>         Marker latitude (default: 38.8977)
  --lon <longitude>        Marker longitude (default: -77.0365)
  --hae <altitude>         Height above ellipsoid in meters (default: 0)
  --callsign <name>        Display name on map (default: "FastTAK Test Stream")
  --stale <minutes>        Minutes until marker expires (default: 60)
  --fov <degrees>          Sensor field of view (default: 60)
  --azimuth <degrees>      Sensor direction 0-360 (default: 0)
  --range <meters>         Sensor visible range (default: 500)
  --server-address <hostname>  Override SERVER_ADDRESS from .env
  --cert <name>            Client cert name (default: nodered)
  --video <file>           Stream a video file instead of the test pattern
  --no-stream              Skip ffmpeg — only send CoT (stream must exist)
  -h, --help               Show this help

Examples:
  ./video-cot.sh                                           # Full test (defaults)
  ./video-cot.sh --video /path/to/video.mp4                # Stream a file
  ./video-cot.sh --no-stream --path cam1                   # Announce existing stream
  ./video-cot.sh --lat 40.709 --lon -73.957 --callsign "Roof Cam"
  ./video-cot.sh --protocol http --port 8888               # HLS instead of RTSP
HELP
    exit 0
}

# ── Parse arguments ──────────────────────────────────────────────────────

# Handle first positional arg as --path for backward compat
case "${1:-}" in
    -h|--help) show_help ;;
    --*)       ;;  # it's a flag, fall through to the loop
    "")        ;;  # no args, use defaults
    *)         STREAM_PATH="$1"; shift ;;
esac

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)   show_help ;;
        --path)      STREAM_PATH="$2";   shift 2 ;;
        --protocol)  PROTOCOL="$2";      shift 2 ;;
        --port)      PORT="$2";          shift 2 ;;
        --lat)       LAT="$2";           shift 2 ;;
        --lon)       LON="$2";           shift 2 ;;
        --hae)       HAE="$2";           shift 2 ;;
        --callsign)  CALLSIGN="$2";      shift 2 ;;
        --stale)     STALE_MINUTES="$2"; shift 2 ;;
        --fov)       FOV="$2";           shift 2 ;;
        --azimuth)   AZIMUTH="$2";       shift 2 ;;
        --range)     RANGE="$2";         shift 2 ;;
        --server-address) SERVER_ADDRESS="$2"; shift 2 ;;
        --cert)      CERT_NAME="$2";     shift 2 ;;
        --video)     VIDEO_FILE="$2";     shift 2 ;;
        --no-stream) TEST_STREAM="false"; shift ;;
        *) echo "Unknown option: $1 (try --help)" >&2; exit 1 ;;
    esac
done

# Default port based on protocol
case "$PROTOCOL" in
    rtsp|rtsps) [ "$PORT" = "8888" ] && PORT="8554" ;;
    http|https) [ "$PORT" = "8554" ] && PORT="8888" ;;
esac

# ── Validate ─────────────────────────────────────────────────────────────

if [ -z "$SERVER_ADDRESS" ]; then
    echo "ERROR: SERVER_ADDRESS not set. Pass --server-address or set it in .env" >&2
    exit 1
fi

CERT_P12="$CERT_DIR/${CERT_NAME}.p12"
CA_PEM="$CERT_DIR/ca.pem"

if [ ! -f "$CERT_P12" ]; then
    echo "ERROR: Client cert not found: $CERT_P12" >&2
    echo "       Certs are generated by TAK Server — run setup.sh first" >&2
    exit 1
fi

# Extract cert and key to temp files
TMPDIR=$(mktemp -d)
cleanup() {
    [ -n "$FFPID" ] && kill "$FFPID" 2>/dev/null
    rm -rf "$TMPDIR"
}
trap cleanup EXIT INT TERM

openssl pkcs12 -in "$CERT_P12" -passin "pass:${CERT_PASS}" \
    -nokeys -out "$TMPDIR/cert.pem" 2>/dev/null
openssl pkcs12 -in "$CERT_P12" -passin "pass:${CERT_PASS}" \
    -nocerts -nodes -out "$TMPDIR/key.pem" 2>/dev/null

# ── Start test stream ───────────────────────────────────────────────────

FFPID=""
if [ -n "$VIDEO_FILE" ]; then
    # --video implies streaming
    if [ ! -f "$VIDEO_FILE" ]; then
        echo "ERROR: Video file not found: $VIDEO_FILE" >&2
        exit 1
    fi
    TEST_STREAM="true"
fi

if [ "$TEST_STREAM" = "true" ]; then
    if ! command -v ffmpeg >/dev/null 2>&1; then
        echo "ERROR: ffmpeg not found. Install it or use --no-stream" >&2
        exit 1
    fi

    # Kill any existing test stream on this path
    pkill -f "rtmp://localhost:1935/${STREAM_PATH}" 2>/dev/null || true
    sleep 1

    if [ -n "$VIDEO_FILE" ]; then
        # Stream a video file on loop
        ffmpeg -re -stream_loop -1 -i "$VIDEO_FILE" \
            -c:v libx264 -profile:v baseline -level 3.1 -pix_fmt yuv420p \
            -preset ultrafast -tune zerolatency -g 30 \
            -c:a aac -b:a 64k \
            -f flv "rtmp://localhost:1935/${STREAM_PATH}" \
            >/dev/null 2>&1 &
    else
        # H.264 Baseline profile + AAC test pattern — compatible with iOS/TAK Aware
        ffmpeg -re \
            -f lavfi -i "testsrc=size=640x480:rate=15" \
            -f lavfi -i "sine=frequency=1000:sample_rate=44100" \
            -c:v libx264 -profile:v baseline -level 3.1 -pix_fmt yuv420p \
            -preset ultrafast -tune zerolatency -g 30 \
            -c:a aac -b:a 64k \
            -f flv "rtmp://localhost:1935/${STREAM_PATH}" \
            >/dev/null 2>&1 &
    fi
    FFPID=$!

    # Wait for MediaMTX to pick up the stream
    sleep 3
    if ! kill -0 "$FFPID" 2>/dev/null; then
        echo "ERROR: ffmpeg exited — is MediaMTX accepting RTMP on port 1935?" >&2
        exit 1
    fi
    echo "Streaming ${VIDEO_FILE:-test pattern} (ffmpeg PID $FFPID)"
fi

# ── Build CoT XML ────────────────────────────────────────────────────────

NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
if command -v gdate >/dev/null 2>&1; then
    STALE=$(gdate -u -d "+${STALE_MINUTES} minutes" +"%Y-%m-%dT%H:%M:%SZ")
elif date -v+1M >/dev/null 2>&1; then
    STALE=$(date -u -v+"${STALE_MINUTES}"M +"%Y-%m-%dT%H:%M:%SZ")
else
    STALE=$(date -u -d "+${STALE_MINUTES} minutes" +"%Y-%m-%dT%H:%M:%SZ")
fi

FEED_UID="FastTAK-video-$(echo "$STREAM_PATH" | tr '/' '-')"

# Build the URL path based on protocol
case "$PROTOCOL" in
    http|https) STREAM_URL_PATH="/${STREAM_PATH}/" ;;
    *)          STREAM_URL_PATH="/${STREAM_PATH}" ;;
esac

COT_XML="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
<event version=\"2.0\" uid=\"${FEED_UID}\" type=\"b-m-p-s-p-loc\" how=\"h-g-i-g-o\" \
time=\"${NOW}\" start=\"${NOW}\" stale=\"${STALE}\">\
<point lat=\"${LAT}\" lon=\"${LON}\" hae=\"${HAE}\" ce=\"9999999\" le=\"9999999\"/>\
<detail>\
<contact callsign=\"${CALLSIGN}\"/>\
<sensor fov=\"${FOV}\" azimuth=\"${AZIMUTH}\" range=\"${RANGE}\" \
hideFov=\"true\" fovRed=\"1\" fovGreen=\"1\" fovBlue=\"0\" fovAlpha=\"0.3\"/>\
<__video url=\"${PROTOCOL}://${SERVER_ADDRESS}:${PORT}${STREAM_URL_PATH}\">\
<ConnectionEntry networkTimeout=\"12000\" uid=\"${FEED_UID}\" \
path=\"${STREAM_URL_PATH}\" protocol=\"${PROTOCOL}\" bufferTime=\"-1\" \
address=\"${SERVER_ADDRESS}\" port=\"${PORT}\" roverPort=\"-1\" rtspReliable=\"0\" \
alias=\"${CALLSIGN}\"/>\
</__video>\
<remarks>Video feed via FastTAK MediaMTX</remarks>\
</detail></event>"

# ── Send to TAK Server ───────────────────────────────────────────────────

python3 -c "
import ssl, socket, time

ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
ctx.load_cert_chain('${TMPDIR}/cert.pem', '${TMPDIR}/key.pem')
ctx.load_verify_locations('${CA_PEM}')
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

sock = socket.create_connection(('localhost', 8089), timeout=10)
ssock = ctx.wrap_socket(sock)
ssock.sendall('''${COT_XML}'''.encode())
time.sleep(2)
ssock.close()
"

echo "Sent video CoT to TAK Server:"
echo "  Callsign: ${CALLSIGN}"
echo "  Stream:   ${PROTOCOL}://${SERVER_ADDRESS}:${PORT}${STREAM_URL_PATH}"
echo "  Position: ${LAT}, ${LON}"
echo "  Stale:    ${STALE_MINUTES} minutes"
echo "  UID:      ${FEED_UID}"

if [ -n "$FFPID" ]; then
    echo ""
    echo "Streaming... Ctrl-C to stop."
    wait "$FFPID"
fi
