"""Tests for app.api.health.certs — certificate expiry parsing."""

import re
from datetime import UTC, datetime, timedelta
from pathlib import Path
from unittest.mock import MagicMock, patch


class TestParseCertExpiry:
    @patch("app.api.health.certs.subprocess.run")
    def test_parses_valid_cert(self, mock_run):
        future = datetime.now(UTC) + timedelta(days=365)
        expiry_str = future.strftime("%b %d %H:%M:%S %Y GMT")
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout=f"subject= CN = tak-server\nnotAfter={expiry_str}",
        )

        from app.api.health.certs import _parse_cert_expiry

        result = _parse_cert_expiry(Path("/fake/cert.pem"))
        assert result is not None
        assert result["days_left"] >= 364
        assert "status" not in result
        # expires is date-only: YYYY-MM-DD
        assert re.match(r"\d{4}-\d{2}-\d{2}$", result["expires"])

    @patch("app.api.health.certs.subprocess.run")
    def test_expired_cert_has_negative_days_left(self, mock_run):
        past = datetime.now(UTC) - timedelta(days=1)
        expiry_str = past.strftime("%b %d %H:%M:%S %Y GMT")
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout=f"subject= CN = test\nnotAfter={expiry_str}",
        )

        from app.api.health.certs import _parse_cert_expiry

        result = _parse_cert_expiry(Path("/fake/cert.pem"))
        assert result["days_left"] < 0

    @patch("app.api.health.certs.subprocess.run")
    def test_returns_none_on_failure(self, mock_run):
        mock_run.return_value = MagicMock(returncode=1, stdout="")

        from app.api.health.certs import _parse_cert_expiry

        assert _parse_cert_expiry(Path("/fake/cert.pem")) is None


class TestCategorize:
    def test_ca_cert_is_infrastructure(self):
        from app.api.health.certs import _categorize_cert

        assert _categorize_cert("ca.pem") == "infrastructure"

    def test_root_ca_is_infrastructure(self):
        from app.api.health.certs import _categorize_cert

        assert _categorize_cert("root-ca.pem") == "infrastructure"

    def test_takserver_is_infrastructure(self):
        from app.api.health.certs import _categorize_cert

        assert _categorize_cert("takserver.pem") == "infrastructure"

    def test_fqdn_server_cert_is_infrastructure(self):
        from app.api.health.certs import _categorize_cert

        assert _categorize_cert("mbp.fold-harmonic.ts.net.pem") == "infrastructure"

    def test_ca_trusted_is_infrastructure(self):
        from app.api.health.certs import _categorize_cert

        assert _categorize_cert("ca-trusted.pem") == "infrastructure"

    def test_svc_cert_is_service(self):
        from app.api.health.certs import _categorize_cert

        assert _categorize_cert("svc_fasttakapi.pem") == "service"

    def test_svc_nodered_is_service(self):
        from app.api.health.certs import _categorize_cert

        assert _categorize_cert("svc_nodered.pem") == "service"

    def test_user_cert_is_user(self):
        from app.api.health.certs import _categorize_cert

        assert _categorize_cert("epound-tablet.pem") == "user"

    def test_plain_username_is_user(self):
        from app.api.health.certs import _categorize_cert

        assert _categorize_cert("jsmith.pem") == "user"

    def test_admin_cert_is_user(self):
        from app.api.health.certs import _categorize_cert

        # admin.pem is a client cert generated by makeCert.sh, not infrastructure
        assert _categorize_cert("admin.pem") == "user"


class TestGetCertStatus:
    @patch("app.api.health.certs.CERT_DIR", Path("/nonexistent/certs"))
    def test_returns_empty_when_dir_missing(self):
        from app.api.health.certs import get_cert_status

        result = get_cert_status()
        assert result == {"items": []}

    @patch("app.api.health.certs._parse_cert_expiry")
    @patch("app.api.health.certs.CERT_DIR")
    def test_items_include_category(self, mock_dir, mock_parse):
        mock_dir.exists.return_value = True
        mock_dir.glob.return_value = [Path("/certs/ca.pem"), Path("/certs/svc_bot.pem")]
        mock_parse.side_effect = [
            {"file": "ca.pem", "subject": "CN=CA", "expires": "2036-01-01", "days_left": 3650},
            {
                "file": "svc_bot.pem",
                "subject": "CN=svc_bot",
                "expires": "2027-01-01",
                "days_left": 300,
            },
        ]

        from app.api.health.certs import get_cert_status

        result = get_cert_status()
        assert len(result["items"]) == 2
        assert result["items"][0]["category"] == "infrastructure"
        assert result["items"][1]["category"] == "service"

    @patch("app.api.health.certs._parse_cert_expiry")
    @patch("app.api.health.certs.CERT_DIR")
    def test_user_certs_excluded_from_items(self, mock_dir, mock_parse):
        mock_dir.exists.return_value = True
        mock_dir.glob.return_value = [
            Path("/certs/ca.pem"),
            Path("/certs/epound-tablet.pem"),
        ]
        mock_parse.side_effect = [
            {"file": "ca.pem", "subject": "CN=CA", "expires": "2036-01-01", "days_left": 3650},
            {
                "file": "epound-tablet.pem",
                "subject": "CN=epound",
                "expires": "2027-01-01",
                "days_left": 300,
            },
        ]

        from app.api.health.certs import get_cert_status

        result = get_cert_status()
        # User certs should be excluded from health monitoring
        assert len(result["items"]) == 1
        assert result["items"][0]["file"] == "ca.pem"
